#ifndef LIBLCRT_HPP
#define LIBLCRT_HPP

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>


struct LcrtArea;

struct LcrtMessage {
  uint8_t *data;
  size_t len;
};

struct LcrtConfig {
  /**
   * Must be non-zero.
   */
  uint16_t k;
  double radius;
  float bitrate_capacity;
  /**
   * Nanoseconds.
   */
  uint64_t construct_timeout;
  /**
   * Nanoseconds.
   */
  uint64_t source_construct_timeout;
};

struct LcrtPosition {
  double x;
  double y;
  double z;
};

struct LcrtNodeInfo {
  void *ctx;
  LcrtPosition (*position)(void *ctx);
  float (*current_bitrate)(void *ctx);
  uint16_t (*interfering_neighbours)(void *ctx);
};


extern "C" {

void lcrt_area_drop(LcrtArea *area);

bool lcrt_area_get_hop_distance(const LcrtArea *area, uint16_t *hop_distance);

void lcrt_area_handle_message(LcrtArea *area,
                              LcrtMessage incoming,
                              LcrtMessage *message,
                              uint64_t *delay);

void lcrt_area_handle_timeout(LcrtArea *area, LcrtMessage *message, uint64_t *delay);

bool lcrt_area_is_forwarder(const LcrtArea *area, uint32_t dst);

bool lcrt_area_is_parent(const LcrtArea *area, uint32_t last_forwarder);

LcrtArea *lcrt_area_new(LcrtConfig config, LcrtNodeInfo node, uint32_t address, uint32_t group);

LcrtArea *lcrt_area_source_new(LcrtConfig config,
                               LcrtNodeInfo node,
                               uint32_t address,
                               uint32_t group,
                               LcrtMessage *message,
                               uint64_t *delay);

void lcrt_debug_config(LcrtConfig config);

void lcrt_message_drop(LcrtMessage m);

LcrtMessage lcrt_message_new(size_t len);

}  // extern "C"

#endif  // LIBLCRT_HPP
