#ifndef LIBLCRT_H
#define LIBLCRT_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>


typedef struct LcrtArea LcrtArea;

typedef struct LcrtMessage {
  uint8_t *data;
  size_t len;
} LcrtMessage;

typedef struct LcrtConfig {
  /**
   * Must be non-zero.
   */
  uint16_t k;
  double radius;
  float bitrate_capacity;
  /**
   * Nanoseconds.
   */
  uint64_t construct_timeout;
  /**
   * Nanoseconds.
   */
  uint64_t source_construct_timeout;
} LcrtConfig;

typedef struct LcrtPosition {
  double x;
  double y;
  double z;
} LcrtPosition;

typedef struct LcrtNodeInfo {
  void *ctx;
  struct LcrtPosition (*position)(void *ctx);
  float (*current_bitrate)(void *ctx);
  uint16_t (*interfering_neighbours)(void *ctx);
} LcrtNodeInfo;

void lcrt_area_drop(struct LcrtArea *area);

bool lcrt_area_get_hop_distance(const struct LcrtArea *area, uint16_t *hop_distance);

void lcrt_area_handle_message(struct LcrtArea *area,
                              struct LcrtMessage incoming,
                              struct LcrtMessage *message,
                              uint64_t *delay);

void lcrt_area_handle_timeout(struct LcrtArea *area, struct LcrtMessage *message, uint64_t *delay);

bool lcrt_area_is_forwarder(const struct LcrtArea *area, uint32_t dst);

bool lcrt_area_is_parent(const struct LcrtArea *area, uint32_t last_forwarder);

struct LcrtArea *lcrt_area_new(struct LcrtConfig config,
                               struct LcrtNodeInfo node,
                               uint32_t address,
                               uint32_t group);

struct LcrtArea *lcrt_area_source_new(struct LcrtConfig config,
                                      struct LcrtNodeInfo node,
                                      uint32_t address,
                                      uint32_t group,
                                      struct LcrtMessage *message,
                                      uint64_t *delay);

void lcrt_debug_config(struct LcrtConfig config);

void lcrt_message_drop(struct LcrtMessage m);

struct LcrtMessage lcrt_message_new(size_t len);

#endif  /* LIBLCRT_H */
